const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const uiPath = path.join(ROOT, "src/pwa/code_explainer.js");
const rulesPath = path.join(ROOT, "src/pwa/code_explainer_rules.js");
const outMd = path.join(ROOT, "docs/quality/unknown_next_action_ui_audit_v332_a3.md");
const outJson = path.join(ROOT, "docs/quality/unknown_next_action_ui_audit_v332_a3.json");

const ui = fs.readFileSync(uiPath, "utf8");
const rules = fs.readFileSync(rulesPath, "utf8");

const checks = [
  {
    id: "data_exists",
    ok: /unknownNextActions/.test(rules) && /hasUnknownNextActions/.test(rules),
    focus: "rules result contains unknownNextActions"
  },
  {
    id: "ui_renderer_exists",
    ok: /UNKNOWN_NEXT_ACTION_UI_V332_A3/.test(ui) && /function renderUnknownNextActionsV332A3/.test(ui),
    focus: "code_explainer.js has unknown next-action renderer"
  },
  {
    id: "ui_renderer_called",
    ok: /renderUnknownNextActionsV332A3\(box,\s*result\)/.test(ui),
    focus: "renderRelatedCards calls unknown next-action renderer"
  },
  {
    id: "visible_user_wording",
    ok: /확인할 명령어/.test(ui) && /PowerShell 명령/.test(ui),
    focus: "Korean visible wording tells user what to run"
  },
  {
    id: "commands_rendered_as_pre",
    ok: /unknown-next-action-commands-v332-a3/.test(ui) && /pre\.textContent\s*=\s*commands\.join\("\\n"\)/.test(ui),
    focus: "commands render as newline-separated pre text"
  },
  {
    id: "empty_state_preserved",
    ok: /!matches\.length\s*&&\s*!unknownNextActionCountV332A3/.test(ui),
    focus: "related-card empty state does not hide unknown actions"
  }
];

const failed = checks.filter((check) => !check.ok);
const summary = {
  audit: "V332_A3_UNKNOWN_NEXT_ACTION_UI_AUDIT",
  checks: checks.length,
  ok: checks.length - failed.length,
  failed: failed.length
};

const md = [
  "# V332-A3 Unknown Next Action UI Audit",
  "",
  "Purpose: verify that unknownNextActions generated by the analyzer are visible in the code explainer UI.",
  "",
  "## Summary",
  "",
  "| metric | value |",
  "|---|---:|",
  "| checks | " + summary.checks + " |",
  "| OK | " + summary.ok + " |",
  "| failed | " + summary.failed + " |",
  "",
  "## Checks",
  "",
  "| id | status | focus |",
  "|---|---|---|",
  ...checks.map((check) => "| " + check.id + " | " + (check.ok ? "OK" : "FAIL") + " | " + check.focus + " |")
].join("\n");

fs.writeFileSync(outMd, md, "utf8");
fs.writeFileSync(outJson, JSON.stringify({ summary, checks }, null, 2) + "\n", "utf8");

console.log(summary.audit);
console.log("checks=" + summary.checks);
console.log("ok=" + summary.ok);
console.log("failed=" + summary.failed);
console.log("report=" + path.relative(ROOT, outMd));

checks.forEach((check) => {
  console.log((check.ok ? "OK " : "FAIL ") + check.id + " - " + check.focus);
});

if (failed.length) {
  process.exitCode = 1;
}
