const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const APP = path.join(ROOT, "src", "pwa", "app.js");
const PWA_INDEX = path.join(ROOT, "src", "pwa", "index.html");
const ROOT_INDEX = path.join(ROOT, "index.html");

const OUT_MD = path.join(ROOT, "docs", "quality", "v334_a10s_visible_recommend_label_hotfix.md");
const OUT_JSON = path.join(ROOT, "docs", "quality", "v334_a10s_visible_recommend_label_hotfix.json");

let app = fs.readFileSync(APP, "utf8");
let pwaIndex = fs.readFileSync(PWA_INDEX, "utf8");
let rootIndex = fs.readFileSync(ROOT_INDEX, "utf8");

const changes = [];

function replaceExact(targetName, oldValue, newValue, required = true) {
  const count = app.split(oldValue).length - 1;
  if (count > 0) {
    app = app.split(oldValue).join(newValue);
  }
  changes.push({ target: targetName, count });
  if (required && count === 0) {
    throw new Error("Required replacement not found: " + targetName);
  }
}

function replaceIndexExact(targetName, oldValue, newValue, required = false) {
  const count = pwaIndex.split(oldValue).length - 1;
  if (count > 0) {
    pwaIndex = pwaIndex.split(oldValue).join(newValue);
  }
  changes.push({ target: targetName, count });
  if (required && count === 0) {
    throw new Error("Required index replacement not found: " + targetName);
  }
}

// Side card nearby suggestion badge.
replaceExact(
  "side_card_related_suggestion_badge",
  'makeSideCard(sc, "연관 추천");',
  'makeSideCard(sc, studyToolsTextV334A10N("연관 추천", "Related suggestion"));'
);

// Recommended progress summary.
replaceExact(
  "recommended_summary_return",
  'return "추천 L" + level + " · 안 본 " + unseen + " · 모르겠음 " + confused + " · 맞힘 " + correct + " / " + total;',
  `return isEnglishLocaleV334A10N()
  ? "Recommended L" + level + " · unseen " + unseen + " · not sure " + confused + " · correct " + correct + " / " + total
  : "추천 L" + level + " · 안 본 " + unseen + " · 모르겠음 " + confused + " · 맞힘 " + correct + " / " + total;`
);

// Current/recommended status line.
replaceExact(
  "current_recommended_summary",
  `summary.textContent =
      "현재 " + (currentLevel === "all" ? "전체 레벨" : "L" + currentLevel) +
      " · 추천 " + (recommended === "all" ? "전체" : "L" + recommended) +
      " · " + getRecommendSummary(recommended);`,
  `if (isEnglishLocaleV334A10N()) {
      summary.textContent =
        "Current " + (currentLevel === "all" ? "All levels" : "L" + currentLevel) +
        " · recommended " + (recommended === "all" ? "All" : "L" + recommended) +
        " · " + getRecommendSummary(recommended);
    } else {
      summary.textContent =
        "현재 " + (currentLevel === "all" ? "전체 레벨" : "L" + currentLevel) +
        " · 추천 " + (recommended === "all" ? "전체" : "L" + recommended) +
        " · " + getRecommendSummary(recommended);
    }`
);

// Quick action buttons generated by template HTML.
replaceExact(
  "recommend_start_button_template",
  '<button type="button" id="studyToolsRecommendStartV272">추천 진도로 오늘 10장</button>',
  '<button type="button" id="studyToolsRecommendStartV272">${studyToolsTextV334A10N("추천 진도로 오늘 10장", "Today 10 from recommended level")}</button>'
);

replaceExact(
  "recommend_apply_button_template",
  '<button type="button" id="studyToolsRecommendApplyV272" class="secondary">추천만 적용</button>',
  '<button type="button" id="studyToolsRecommendApplyV272" class="secondary">${studyToolsTextV334A10N("추천만 적용", "Apply recommendation")}</button>'
);

replaceExact(
  "settings_toggle_button_template",
  '<button type="button" id="studyToolsToggleV272" class="secondary">설정 펼치기</button>',
  '<button type="button" id="studyToolsToggleV272" class="secondary">${studyToolsTextV334A10N("설정 펼치기", "Open settings")}</button>'
);

// Mobile micro summary.
replaceExact(
  "micro_recommend_summary",
  'return "추천 " + levelText + " · 남은 " + remaining + " · 큐 " + queueLen + "/10";',
  `return isEnglishLocaleV334A10N()
  ? "Recommended " + (recommended === "all" ? "All" : "L" + recommended) + " · remaining " + remaining + " · queue " + queueLen + "/10"
  : "추천 " + levelText + " · 남은 " + remaining + " · 큐 " + queueLen + "/10";`
);

// Mobile compact buttons.
replaceExact(
  "mobile_recommend_10_button",
  'startBtn.textContent = "추천 10장";',
  'startBtn.textContent = studyToolsTextV334A10N("추천 10장", "Recommended 10");'
);

replaceExact(
  "mobile_apply_recommendation_button",
  'applyBtn.textContent = "추천 적용";',
  'applyBtn.textContent = studyToolsTextV334A10N("추천 적용", "Apply recommendation");'
);

// Static translation map for command next checks, in case the source HTML is translated by dictionary pass.
if (!app.includes('"다음 확인 명령어": "Next check commands"')) {
  replaceExact(
    "add_command_next_checks_static_map",
    '"추천만 적용": "Apply recommendation",',
    `"추천만 적용": "Apply recommendation",
    "다음 확인 명령어": "Next check commands",
    "분석 후 추천 확인 명령이 표시됩니다.": "Recommended follow-up check commands will appear after analysis.",`
  );
} else {
  changes.push({ target: "add_command_next_checks_static_map", count: 0, skipped: true });
}

// Fix corrupted doubled Korean in source HTML.
replaceIndexExact(
  "pwa_index_next_checks_heading_garbled",
  '<h2>다다음음 확확인인 명명령령어어</h2>',
  '<h2>다음 확인 명령어</h2>'
);

replaceIndexExact(
  "pwa_index_next_checks_body_garbled",
  '<div id="commandNextChecks" class="code-related-cards muted">분분석석 후후 추추천천 확확인인 명명령령이이 표시됩니다.</div>',
  '<div id="commandNextChecks" class="code-related-cards muted">분석 후 추천 확인 명령이 표시됩니다.</div>'
);

// Version bump.
app = app.replace(/2026062[23]_v334_a10[a-z]*/g, "20260623_v334_a10s");
pwaIndex = pwaIndex.replace(/2026062[23]_v334_a10[a-z]*/g, "20260623_v334_a10s");
rootIndex = rootIndex.replace(/2026062[23]_v334_a10[a-z]*/g, "20260623_v334_a10s");

fs.writeFileSync(APP, app.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(PWA_INDEX, pwaIndex.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(ROOT_INDEX, rootIndex.replace(/\s+$/g, "") + "\n", "utf8");

const report = {
  audit: "V334_A10S_VISIBLE_RECOMMEND_LABEL_HOTFIX",
  version: "20260623_v334_a10s",
  changes
};

fs.writeFileSync(OUT_JSON, JSON.stringify(report, null, 2) + "\n", "utf8");

const md = [];
md.push("# V334-A10S Visible Recommendation Label Hotfix");
md.push("");
md.push("Purpose: fix visible Korean recommendation labels in EN mode without adding runtime DOM patch layers.");
md.push("");
md.push("## Summary");
md.push("");
md.push("| metric | value |");
md.push("|---|---:|");
md.push("| version | 20260623_v334_a10s |");
md.push("| changed targets | " + changes.filter((c) => c.count > 0).length + " |");
md.push("");
md.push("## Replacement counts");
md.push("");
md.push("| target | count |");
md.push("|---|---:|");
for (const change of changes) {
  md.push("| " + change.target + " | " + change.count + " |");
}

fs.writeFileSync(OUT_MD, md.join("\n") + "\n", "utf8");

console.log("V334_A10S_VISIBLE_RECOMMEND_LABEL_HOTFIX");
console.log("version=20260623_v334_a10s");
console.log("report=" + path.relative(ROOT, OUT_MD));
changes.forEach((change) => console.log(change.target + "=" + change.count));
