const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

const RULES = path.join(ROOT, "src", "pwa", "code_explainer_rules.js");
const CODE = path.join(ROOT, "src", "pwa", "code_explainer.js");
const APP = path.join(ROOT, "src", "pwa", "app.js");
const PWA_INDEX = path.join(ROOT, "src", "pwa", "index.html");
const ROOT_INDEX = path.join(ROOT, "index.html");

const OUT_MD = path.join(ROOT, "docs", "quality", "v334_a11d_code_explainer_visible_en_polish.md");
const OUT_JSON = path.join(ROOT, "docs", "quality", "v334_a11d_code_explainer_visible_en_polish.json");

let rules = fs.readFileSync(RULES, "utf8");
let code = fs.readFileSync(CODE, "utf8");
let app = fs.readFileSync(APP, "utf8");
let pwaIndex = fs.readFileSync(PWA_INDEX, "utf8");
let rootIndex = fs.readFileSync(ROOT_INDEX, "utf8");

const changes = [];

function replaceIn(name, target, oldValue, newValue) {
  let text =
    target === "rules" ? rules :
    target === "code" ? code :
    target === "pwaIndex" ? pwaIndex :
    target === "rootIndex" ? rootIndex :
    app;

  const count = text.split(oldValue).length - 1;
  if (count > 0) text = text.split(oldValue).join(newValue);

  if (target === "rules") rules = text;
  else if (target === "code") code = text;
  else if (target === "pwaIndex") pwaIndex = text;
  else if (target === "rootIndex") rootIndex = text;
  else app = text;

  changes.push({ name, target, count });
}

function replaceRegex(name, target, re, newValue) {
  let text =
    target === "rules" ? rules :
    target === "code" ? code :
    target === "pwaIndex" ? pwaIndex :
    target === "rootIndex" ? rootIndex :
    app;

  const before = text;
  text = text.replace(re, newValue);
  const count = before === text ? 0 : 1;

  if (target === "rules") rules = text;
  else if (target === "code") code = text;
  else if (target === "pwaIndex") pwaIndex = text;
  else if (target === "rootIndex") rootIndex = text;
  else app = text;

  changes.push({ name, target, count });
}

// 1) Add a few missing display translations.
replaceIn(
  "code_display_exact_extra_keys",
  "code",
  '      const exact = {\n',
  '      const exact = {\n' +
  '        "자동 감지": "Auto detect",\n' +
  '        "자동감지": "Auto detect",\n' +
  '        "PowerShell/CLI(터미널 명령) 확인": "PowerShell/CLI terminal command check",\n' +
  '        "터미널 명령": "terminal command",\n' +
  '        "Git": "Git",\n' +
  '        "DB": "DB",\n' +
  '        "프로세스": "process",\n'
);

// 2) Detection chips: translate the selected/detected label values, not only the prefix.
replaceIn(
  "code_selected_chip_value_translate",
  "code",
  'codeExplainerTextV334A11B("선택: ", "Selected: ") + escapeHtml(requestedLabel)',
  'codeExplainerTextV334A11B("선택: ", "Selected: ") + escapeHtml(codeExplainerDisplayTextV334A11C(requestedLabel))'
);

replaceIn(
  "code_detected_chip_value_translate",
  "code",
  'codeExplainerTextV334A11B("감지: ", "Detected: ") + escapeHtml(detectedLabel)',
  'codeExplainerTextV334A11B("감지: ", "Detected: ") + escapeHtml(codeExplainerDisplayTextV334A11C(detectedLabel))'
);

// 3) Summary text generated by code_explainer_rules.js.
if (!rules.includes("function codeRuleTranslateCountItemV334A11D")) {
  replaceIn(
    "rules_insert_count_item_translator",
    "rules",
    '  function codeRuleTranslateExplainV334A11C(title, explain) {\n    if (!codeRuleIsEnglishV334A11B()) return explain;\n\n    const raw = String(explain || "");\n    if (!codeRuleHasKoreanV334A11C(raw)) return raw;\n\n    const enTitle = codeRuleTranslateTitleV334A11C(title);\n    return "This line is interpreted as: " + enTitle + ". Review the original line, paths, options, and surrounding context before running it.";\n  }\n',
    '  function codeRuleTranslateExplainV334A11C(title, explain) {\n    if (!codeRuleIsEnglishV334A11B()) return explain;\n\n    const raw = String(explain || "");\n    if (!codeRuleHasKoreanV334A11C(raw)) return raw;\n\n    const enTitle = codeRuleTranslateTitleV334A11C(title);\n    return "This line is interpreted as: " + enTitle + ". Review the original line, paths, options, and surrounding context before running it.";\n  }\n\n  function codeRuleTranslateCountItemV334A11D(item) {\n    const raw = String(item || "");\n    return raw.replace(/^(.+?)\\s+(\\d+)개$/, function(_, label, count) {\n      return codeRuleTranslateTitleV334A11C(label) + " " + count;\n    });\n  }\n'
  );
} else {
  changes.push({ name: "rules_insert_count_item_translator", target: "rules", count: 0, skipped: true });
}

replaceIn(
  "rules_flow_summary_english",
  "rules",
  'return "주요 흐름: " + ordered.join(" · ");',
  'return codeRuleIsEnglishV334A11B() ? "Main flow: " + ordered.map(codeRuleTranslateCountItemV334A11D).join(" · ") : "주요 흐름: " + ordered.join(" · ");'
);

replaceIn(
  "rules_overall_summary_english",
  "rules",
  'return (names[language] || "코드") + "를 " + steps.length + "단계로 나눠 해석했습니다." + (risky ? " 주의가 필요한 단계가 " + risky + "개 있습니다." : " 특별히 높은 위험 명령은 감지되지 않았습니다.");',
  'return codeRuleIsEnglishV334A11B()\n      ? (names[language] || "Code") + " was explained in " + steps.length + " steps." + (risky ? " " + risky + " caution/risk step(s) were found." : " No high-risk commands were detected.")\n      : (names[language] || "코드") + "를 " + steps.length + "단계로 나눠 해석했습니다." + (risky ? " 주의가 필요한 단계가 " + risky + "개 있습니다." : " 특별히 높은 위험 명령은 감지되지 않았습니다.");'
);

// 4) Top categories/tags and step badges.
replaceIn(
  "code_top_categories_value_translate",
  "code",
  'escapeHtml(overview.topCategories || codeExplainerTextV334A11B("분류 없음", "none"))',
  'escapeHtml(codeExplainerDisplayTextV334A11C(overview.topCategories || codeExplainerTextV334A11B("분류 없음", "none")))'
);

replaceIn(
  "code_top_tags_value_translate",
  "code",
  'escapeHtml(overview.topTags || codeExplainerTextV334A11B("태그 없음", "none"))',
  'escapeHtml(codeExplainerDisplayTextV334A11C(overview.topTags || codeExplainerTextV334A11B("태그 없음", "none")))'
);

replaceRegex(
  "code_step_category_translate_fallback",
  "code",
  /escapeHtml\(step\.category \|\| "처리"\)/g,
  'escapeHtml(codeExplainerDisplayTextV334A11C(step.category || "처리"))'
);

replaceRegex(
  "code_step_category_translate_direct",
  "code",
  /escapeHtml\(step\.category\)/g,
  'escapeHtml(codeExplainerDisplayTextV334A11C(step.category))'
);

replaceRegex(
  "code_tag_translate_direct",
  "code",
  /escapeHtml\(tag\)/g,
  'escapeHtml(codeExplainerDisplayTextV334A11C(tag))'
);

replaceRegex(
  "code_plain_report_tags_translate",
  "code",
  /step\.tags\.join\(" #"\)/g,
  'step.tags.map(codeExplainerDisplayTextV334A11C).join(" #")'
);

// 5) Check-command card visible Korean.
replaceIn(
  "code_check_action_title_literal",
  "code",
  '"PowerShell/CLI(터미널 명령) 확인"',
  'codeExplainerTextV334A11B("PowerShell/CLI(터미널 명령) 확인", "PowerShell/CLI terminal command check")'
);

replaceIn(
  "code_compress_archive_check_reason_literal",
  "code",
  '"Compress-Archive 명령이 설치된 도구인지, 스크립트인지, 위험한 옵션이 있는지 확인해야 합니다."',
  'codeExplainerTextV334A11B("Compress-Archive 명령이 설치된 도구인지, 스크립트인지, 위험한 옵션이 있는지 확인해야 합니다.", "Check whether Compress-Archive is an installed command, script, or command with risky options.")'
);

replaceIn(
  "code_generic_terminal_check_reason_literal",
  "code",
  '"명령이 설치된 도구인지, 스크립트인지, 위험한 옵션이 있는지 확인해야 합니다."',
  'codeExplainerTextV334A11B("명령이 설치된 도구인지, 스크립트인지, 위험한 옵션이 있는지 확인해야 합니다.", "Check whether the command is an installed tool, a script, or has risky options.")'
);

// 6) Mermaid placeholder help text in static PWA HTML.
replaceIn(
  "pwa_flowchart_lazy_help_text",
  "pwaIndex",
  '흐름도는 필요할 때만 생성합니다. 먼저 설명을 읽고, 흐름이 필요하면 아래에서 흐름도 보기를 누르세요.',
  'Flowcharts are generated only when needed. Read the explanation first, then use the button below if you need the flow.'
);

// 7) Version bump.
app = app.replace(/2026062[23]_v334_a11[a-z]*/g, "20260623_v334_a11d");
pwaIndex = pwaIndex.replace(/2026062[23]_v334_a11[a-z]*/g, "20260623_v334_a11d");
rootIndex = rootIndex.replace(/2026062[23]_v334_a11[a-z]*/g, "20260623_v334_a11d");

fs.writeFileSync(RULES, rules.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(CODE, code.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(APP, app.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(PWA_INDEX, pwaIndex.replace(/\s+$/g, "") + "\n", "utf8");
fs.writeFileSync(ROOT_INDEX, rootIndex.replace(/\s+$/g, "") + "\n", "utf8");

const report = {
  audit: "V334_A11D_CODE_EXPLAINER_VISIBLE_EN_POLISH",
  version: "20260623_v334_a11d",
  changes
};

fs.writeFileSync(OUT_JSON, JSON.stringify(report, null, 2) + "\n", "utf8");

const md = [];
md.push("# V334-A11D Code Explainer Visible EN Polish");
md.push("");
md.push("Purpose: polish remaining visible Korean in Code explainer after A11C.");
md.push("");
md.push("## Summary");
md.push("");
md.push("| metric | value |");
md.push("|---|---:|");
md.push("| version | 20260623_v334_a11d |");
md.push("| changed targets | " + changes.filter((c) => c.count > 0).length + " |");
md.push("");
md.push("## Replacement counts");
md.push("");
md.push("| target | file | count |");
md.push("|---|---|---:|");
for (const c of changes) {
  md.push("| " + c.name + " | " + c.target + " | " + c.count + " |");
}

fs.writeFileSync(OUT_MD, md.join("\n") + "\n", "utf8");

console.log("V334_A11D_CODE_EXPLAINER_VISIBLE_EN_POLISH");
console.log("version=20260623_v334_a11d");
console.log("report=" + path.relative(ROOT, OUT_MD));
changes.forEach((c) => console.log(c.name + "=" + c.count));
